services:
  # Backend da API ML
  backend:
    build: 
      context: ./back-end
      dockerfile: Dockerfile
    container_name: fetalcare-backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - DEBUG=False
    volumes:
      - ./back-end/IA:/app/IA:ro  # Volume read-only para o modelo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Frontend web
  frontend:
    image: nginx:alpine
    container_name: fetalcare-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./front-end:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
    restart: unless-stopped

networks:
  default:
    name: fetalcare-network 